-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg7zsxi7LB4uP+mskc
8fShmqfIvG61cJvDUkBIDt0obfWgCgYIKoZIzj0DAQehRANCAAQC7GSGxrKmjjCC
BkXz4EO+0Gk5UQYMPcEPnIMVdkgooPf+VT3+SYUH69cN0xhKgYWz7v3PldbYa/Yf
luexYfBU
-----END PRIVATE KEY-----